### ISSUE TITLE
Maybe a bug in 'bootleg_annotator.py'

### ISSUE THREAD

**Issue by lypl** [HazyResearch/bootleg#100]
Hi, I found that there is a bug about path of loading entitydb data when I use this tool ;)
In function 'create_config()' of 'bootleg_annotator.py':
`config_args["data_config"]["alias_cand_map"] = "alias2qids.json"`
should be:
`config_args["data_config"]["alias_cand_map"] = "alias2qids"`

**Comment by lorr1** [comment]
Thank for pointing this out. I'll fix this in the next PR.
