### ISSUE TITLE
Published PyPI module is out of date

### ISSUE THREAD

**Issue by chanind** [HazyResearch/bootleg#106]
The most recent version of [bootleg on PyPI](https://pypi.org/project/bootleg/) is version 1.0.5 from August, 2021. However, this project has changed a lot since then, including a large architecture change (according to the readme). It also appears that the version of bootleg on PyPI no longer works with the latest models and data for this project. Is it possible to update the PyPI release of this project to use the most recent code from this repo?

**Comment by lorr1** [comment]
Just pushed 1.1.0 to pypi.

**Comment by chanind** [comment]
🎉  Thank you so much!
