### ISSUE TITLE
Do you update the knowledge graph periodically ?

### ISSUE THREAD

**Issue by coolcoder001** [HazyResearch/bootleg#115]
Hi @lorr1 / @chanind / @xiaoling / @stephenbach / @senwu / @vincentschen ,

When you update/push new version of bootleg, do you also publish a new dataset (KG dataset to be precise)?

Basically , how frequently do you update the entity_db file ? Do you scrape wikidata periodically and append to the entity_db?

**Comment by lorr1** [comment]
So if I release a model again, it will be over a newer version of the KG data, too. However, I don't have any immediate plans to retrain and release a new version of teh model.

**Comment by coolcoder001** [comment]
> So if I release a model again, it will be over a newer version of the KG data, too. However, I don't have any immediate plans to retrain and release a new version of teh model.

Hi @lorr1 ,
so, in that case, I should use your other project (https://github.com/lorr1/bootleg_data_prep) , to download the data and retrain the model. Right ?

**Comment by lorr1** [comment]
Yes, that's correct!
