### ISSUE TITLE
Question about AIDA-CoNLL data

### ISSUE THREAD

**Issue by hitercs** [HazyResearch/bootleg#14]
Hi,

Is there any possibility to get your processed AIDA-CoNLL dataset used in the experiment?
Thanks!

**Comment by lorr1** [comment]
Yes. Happy to share that with you. Do you want the Pershina candidate lists, too or just the raw AIDA data that has been mapped to QIDs?

**Comment by hitercs** [comment]
@lorr1 Thanks! The CoNLL data with Pershina candidate lists (just like your kore50 and rss500 files) would be appreciated.

**Comment by lorr1** [comment]
So, I just remembered that the AIDA data requires a signed agreement (https://trec.nist.gov/data/reuters/reuters.html) so I can't release the data to you, but I can share with you our scripts we used to process it so that once you have the data you can easily regenerate it.

**Comment by hitercs** [comment]
@lorr1 That would be great. Thank you!

**Comment by lorr1** [comment]
@hitercs is there some email I can use to send you the scripts and our downloaded Pershina files.

**Comment by hitercs** [comment]
Thanks!, my email is hitercs@gmail.com .

**Comment by raaupr** [comment]
Hi! Sorry to "re-open" the thread, but may I also get the scripts and Pershina files? Thank you!
