### ISSUE TITLE
Question about the train slices, eval slices and train heads

### ISSUE THREAD

**Issue by hitercs** [HazyResearch/bootleg#15]
Hi,

Thanks for your great work. 
When I read the code, it is a bit difficult for me to understand the design logic behind the following concepts: _train heads_, _train slices_ and _eval slices_. 
I found the main setup code and comments are in this section. https://github.com/HazyResearch/bootleg/blob/252efc64a0a830b6fdd41a716a7abc00bb0dbc5b/bootleg/utils/train_utils.py#L114

Could you please elaborate more about:

1. what is _train heads_, _train slices_ and _eval slices_?
2. it seems there are two _slice_method_ (Normal and SBL), what does they stand for?
3. could you please explain more about the taxonomy and why it designs like that?

>     If SBL (has base head loss):
>         train_heads must include BASE_SLICE and not include FINAL_LOSS
>         eval_slices must include BASE_SLICE and FINAL_LOSS
>     If Normal:
>         train_heads can include those from the args (these train heads will be used to evaluate filter/ranking capabilities)
>         eval_slices must include FINAL_LOSS and can include BASE_SLICE

Thanks a lot.

**Comment by lorr1** [comment]
Yes. So that part of our code was slightly more experimental and none of our released models use the the `SBL` part.

**Comment by hitercs** [comment]
Thanks! Really appreciate the detailed explanation! I learnt more about that.
