### ISSUE TITLE
Conda installation instructions result in ResolvePackageNotFound

### ISSUE THREAD

**Issue by sujitpal** [HazyResearch/bootleg#18]
Output is as follows:
```
$ conda env create --name bootleg_dev --file conda_requirements.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - torch[version='1.6.0.*,1.6.0.*']
  - tagme=0.1.3
  - transformers=3.0.1
  - marisa-trie=3.1.1
```

Conda version: 4.9.2
Python version (Anaconda): 3.8.5
CUDA version: 10.2
Output of nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

Installing using `pip install -r requirements.txt` also results in the following error message, but seems to build everything so that the `python setup.py develop` completes without error.
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

python-language-server 0.35.1 requires ujson>=3.0.0; python_version > "3", but you'll have ujson 1.35 which is incompatible.
python-jsonrpc-server 0.4.0 requires ujson>=3.0.0, but you'll have ujson 1.35 which is incompatible.
```

**Comment by lorr1** [comment]
Hello Sujit!

We'll look into the conda issue. As for pip, I can modify the requirements to be more flexible for ujson. The exact version of ujson should not matter. Out of curiosity, what python version are you using?

**Comment by sujitpal** [comment]
Hi @lorr1 thank you for looking into this. I am using Anaconda Python version 3.8.5. One other minor documentation nit -- after the conda create environment command, I think that we have to `conda activate <env_name>` before running the `python setup.py develop` command.

**Comment by lorr1** [comment]
We just pushed a fix https://github.com/HazyResearch/bootleg/pull/20 that modifies the conda environment. This should fix the dependency issues.

Let us know if you have any other issues with environments and we can reopen this.
