### ISSUE TITLE
Question : Wikipedia / Wikidata Aliases

### ISSUE THREAD

**Issue by antonyscerri** [HazyResearch/bootleg#22]
Hi

Whilst experimenting with bootleg over some literature we noted that some entities we'd expect to find were not being picked up. For example "apoptosis", so I did a little digging in the aliases file (specifically alias2qids_wiki.json which was referenced in the example configs) and the term was not present. The word is included as parts of other terms but not by itself. There is a wikipedia page for that concept and has the same title (https://en.wikipedia.org/wiki/Apoptosis) and there is a corresponding wikidata entry https://www.wikidata.org/wiki/Q14599311 however it has a different title, it does however have apoptosis as a label several times.

I noted there was also the file alias2qids.json which was slightly bigger file and did include the term. However trying that file instead produced a lot more mentions tags but for a lot of irrelevant terms (including basics words like "of", "also", "from" etc). I wondered if you were aware of the loss of terms like apoptosis and whether that was the result of filtering them other down at some stage or you had a generation process which might have dropped it for some other reason (I couldn't tell whether you used a particular source from another project or not).

On a side note what is the best explanation of each source dataset and its derived forms and subsequent processed (into models, embeddings etc) and when each one is used? There are a lot of files and its not always clear when one is required or used (particularly those in the prep subfolders) and as to when you could substitute or modify one and which steps it would need feeding into (for example can you change the alias terms to some extent without having to retrain everything).

Thanks

Tony

**Comment by lorr1** [comment]
Hello Tony,

We do some heuristic filtering on our alias2qid mapping to try to filter away, as you pointed out, noisy mentions. Our heuristic is to use Wikipedia and measure how often a term appears compared to how often it appears as a labeled mentioned. If it appears as a mention less than <~3% of the time, we filter it out. It's heuristic so we do miss some. This is great feedback for us. We are working on getting a new release of model and code changes out soon and we will be recreating these alias mappings. We'll use apoptosis as a good sanity check for our filtering.

Adding @mleszczy who is working on making the mention extraction and candidate generation portion of our model learned so we don't have to rely on alias2qid mappings.

So for the data question, are you more interested in how it goes from raw data (i.e., Wikipedia dump) to input data files (e.g., alias2qid.json) or how it goes from input data files to actually being used by the model. I'm trying to think of the best way to best share/explain this. The high-level diagram in our README gives some sense as to what impacts the model or not, but it isn't detailed in terms of files/inputs.

To answer your question at the very end, you can easily modify alias2qids.json and that won't impact the model. You _will_ have to either set `data_config.overwrite_preprocessed_data` to be True or remove the prepped alias mapping file (in `entity_dir/prep_dir`) so we overwrite our saved one and use the modified one. Alternatively, you can rename the file to be like `alias2qid_new.json` and if you have the config point to that file, then it'll also reprep it.

Also happy to hop on a call at any time to discuss more questions if it helps. We can connect via email.

**Comment by antonyscerri** [comment]
Thanks for the explanation on the filtering. Looking at alternatives that don't require fixed term lists some ML based NER style tagger up front I assume, would be great to see.

Re data it was getting to see which files are really used during inference vs training (or both) and for what purpose. Things like the alias file clearly are used at inference right now as well I assume at some stage for training in some manner (building one of the embedding layers. As you pointed out it will rebuild certain files and as there were many files in prep directories downloaded already it was a matter of tracing code to find out which might be being used. This was really to help with determining what we might be able to change at inference time to change which entities might be recognised (like the alias input for tagging), are there other static files (separate from any trained model) and which would require retraining. So how flexible the system might be to changing corpora and entity vocab (for example using it to resolve to something other than QID if an appropriate file could be fed in). I appreciate this might be quite a detailed response, at this point given things are still in development, so happy to wait on this.

As I mentioned i tried switching out alias2qid for alias2qid_wiki in the config and I assume because its a different file name it rebuilt the necessary pieces as it did effect the results with having to delete anything or setting overwrite to true. I believe the entiy extractor currently loads the raw file into a trie every time.

Thanks for the offer of hoping on a call or email, if the need should arise i'll follow up separately.

**Comment by lorr1** [comment]
Hey Tony. You're asking great questions and we actually have a student who is working on how to build personalized NED models that merge together Wikipedia entities with personal entities (e.g., business employees). Would like to hear more about your use case.

At a high level, any input that is a map from one vocab to another (e.g., alias -> QID, QID -> type ID, QID -> relation ID, ...) can technically be swapped out dynamically with no harm. Anything that build an index map and isn't learned in any way is fine. Some of these mappings are saved at registered buffers in the model (or will be in a soon to come code release) which makes changing out these mappings a little more complicated than just recreating a json, but is totally doable. We can even provide some scripts to help with this.

Now, changing anything that is related to a learned embedding is more tricky. For example, adding new entities or types. It's doable but more complex and, unless you want the embedding to be random, will need to be trained. This is an interesting question, too? How do you train a model to learn new information without forgetting old. The student I mentioned is actively thinking about this, too.

We're working on some readthedocs more formal documentation. We'll try to add some more details there, too, so when we push out this new release, there will hopefully be more information.

**Comment by lorr1** [comment]
Let me know if you have any more questions. I'll reopen issue.
