### ISSUE TITLE
model_eval hangs

### ISSUE THREAD

**Issue by ADMoreau** [HazyResearch/bootleg#23]
Hello, I'm working in colab, using a GPU (Tesla T4) following the end-to-end tutorial https://github.com/HazyResearch/bootleg/blob/252efc64a0a830b6fdd41a716a7abc00bb0dbc5b/tutorials/end2end_ned_tutorial.ipynb when I get to 

bootleg_label_file, bootleg_emb_file = run.model_eval(args=config_args, mode="dump_embs", logger=logger, is_writer=True)

the program hangs on 

2021-02-01 20:44:09,465 Loading entity_symbols...
2021-02-01 20:45:11,355 Loaded entity_symbols with 5310039 entities.
2021-02-01 20:45:12,633 Loading slices...

previous attempts to run the same code using only CPU, the colab notebook ran overnight and was also stuck at the same point in the code.

Thank you

**Comment by lorr1** [comment]
Hello!

Can you give us a little more information on the specs of the system? Also, are there any log files you have that you can share? If I had to totally guess, it'd me that there isn't enough CPU memory, but I am not sure how much you have.

**Comment by ADMoreau** [comment]
Hi, thanks for the timely response. The following notebook was ran on colab with a cpu https://colab.research.google.com/gist/ADMoreau/47adce28b659e7cf768e0f564b3e2b54/untitled18.ipynb

Here are the logs which don't display any errors after starting the notebook 
![Screenshot from 2021-02-02 17-54-32](https://user-images.githubusercontent.com/27705902/106678839-23c17680-6581-11eb-8f7f-525079efc2b2.png)

And here are the specs
![Screenshot from 2021-02-02 18-01-13](https://user-images.githubusercontent.com/27705902/106678870-30de6580-6581-11eb-8f69-5b9d7d7d5af3.png)

**Comment by lorr1** [comment]
Hey! Thanks for the screenshots. YA the log isn't that helpful from the notebook. However, it looks like the machine only has around 12GB of memory? Is that correct? You'll likely need a machine that has at least 30 GB of memory to load and run without issues. Is that possible with your setup on colab?

**Comment by ADMoreau** [comment]
Yes there is only 12GB, I didn't realize that 30 was necessary. I can't get that much RAM in a colab notebook. Thank you for your help clarifying this.
