### ISSUE TITLE
Couldn't handle unknown alias in test time

### ISSUE THREAD

**Issue by hitercs** [HazyResearch/bootleg#50]
Hi,

Thanks for your work. 
I found one potential problem of current pipeline is that it couldn't handle unknown alias in test time. As shown in this code,
https://github.com/HazyResearch/bootleg/blob/2189b6080cec597e0c69fe3a3d1400cd5f27454a/bootleg/datasets/dataset.py#L686
it assumes the alias is in the alias map. 

However, in practice, if we already have a test set with detected mentions and want to run bootleg over it with _dump_preds_ mode. It is very likely to encoder unknown alias. Could you please consider to replace the assertion with a PAD alias to make it possible to run.

**Comment by lorr1** [comment]
Hello,

Yes, I can make that change. This is a use case we should support. However, I think we'd not want a PAD alias. PAD aliases are ignored by the scorer, meaning those would not be in the denominator. We do want these in the denominator (so we count them as incorrect as we didn't manifest candidates for them).

Let me play around with things about the best way to do this.

**Comment by hitercs** [comment]
That's great, thanks!

**Comment by lorr1** [comment]
Added unk alias support in #51 . Will have it pushed out publicly with our next release.
