### ISSUE TITLE
Languages Supported

### ISSUE THREAD

**Issue by rubmz** [HazyResearch/bootleg#66]
Hey Guys! EPIC Project🥇 

Consider this a suggestion for improvement rather than a bug...

It would be nice if you could state anywhere in your documentations/readme which language are supported by this package (even if training and testing will still be required by anyone wishes to add a language). It's important for anyone coming from other low resource languages such as Hebrew or Arabic. It's hard to know if a package may contain any language specific requirements one cannot provide for a certain language.

Thanks.

**Comment by lorr1** [comment]
Hello,

Great suggestion. Thank you. The model right now is geared towards English, but I have trained ones in other languages before. I'll add this to the README for future folks. I have a private repo I'm happy to share that has a data prep pipeline for multilingual data from Wikipedia + Wikidata, too. Although handling resource poor languages is still a really hard problem.

**Comment by rubmz** [comment]
If the project based upon BERT it should be feasible for most languages. There is GENRE which is based on BART (which has limited language availability) and I am almost sure that bootleg is language independent. Wikipedia and wikidata are avaiable in almost any language. So it really comes down to the base models + configuration limitations.
And - Thanks for taking this language doc request seriously!

**Comment by lorr1** [comment]
Of course. I just added a section at the end of the readme about language supports. It's a great idea. And you're right. As long as there is some Wikipeida data and Wikidata data for that language, it should work. I also think if we did some multi-lingual joint training (or domain transfer), we could possibly improve on resource poor languages that don't have a lot of Wikipedia text.
