### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by lshowway** [HazyResearch/bootleg#99]
I installed bootleg by
 `git clone git@github.com:HazyResearch/bootleg bootleg
cd bootleg
python3 setup.py install`
but when i run `ann = BootlegAnnotator()`, it reports

`[Errno 2] No such file or directory: 'bootleg\\data\\entity_db\\entity_mappings\\alias2qids.json'`

**Comment by lorr1** [comment]
Hello, I just pushed a fix to the master branch to fix this. It should just be alias2qids.
